tasks:
  - init: export PIP_USER=false && pip install --upgrade pip setuptools wheel && pip install poetry && poetry install && poetry run pre-commit install && pre-commit run --all-files
    command: poetry shell
