repos:
  - repo: local
    hooks:
      - id: auto-format
        name: auto-format
        entry: doit
        args: [auto_format]
        language: python
        types: [python]
        pass_filenames: false
      - id: lint
        name: lint
        entry: doit
        args: [lint]
        language: python
        types: [python]
        pass_filenames: false
      - id: test
        name: test
        entry: doit
        args: [test]
        language: python
        types: [python]
        pass_filenames: false
  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        name: commitizen-commit-message-check
        stages: [commit-msg]
