name: Python package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install poetry
          poetry install
          poetry shell
      - name: Auto format
        run: |
          isort .
          add-trailing-comma ./**/*.py
          pyformat --in-place ./**/*.py
      - name: Lint and test
          run: |
            safety check
            flakehell lint
            pytest
            mypy ./**/*.py
