name: Python auto format, lint and codecov

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1.1.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: poetry install
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
    - name: Auto format
      run: |
        poetry run pyformat --in-place ./**/*.py
        poetry run autoflake --in-place ./**/*.py
        poetry run isort ./**/*.py
        poetry run add-trailing-comma ./**/*.p
    - name: Lint and dependencies security check
      run: |
        poetry run safety check
        poetry run flakehell lint cakemix/ tests/
        poetry run mypy ./**/*.py
    - name: Test with pytest
      run: poetry run pytest --cov=cakemix --cov-report=xml
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
